# Dataframe

In [2]:
import pandas as pd
import numpy as np

In [18]:
# creating an array

# 1st way of creating an array
# data = np.array([["Ashwin",32],["Niveda",33],["Julia",23]])

# 2nd way of creating an array
data = [["Vedhanth",5],["Ashwin",32],["Niveda",33],["Jayanthi",59],["Julia",23],["Aravinth",32]]

In [19]:
# creating a dataframe
df = pd.DataFrame(data,index=['1','2','3','4','5','6'],columns=['Name','Age'])

In [20]:
# display dataframe
df

       Name  Age
1  Vedhanth    5
2    Ashwin   32
3    Niveda   33
4  Jayanthi   59
5     Julia   23
6  Aravinth   32

In [22]:
states=['Tamil Nadu','Karnataka','Kerala','A.P','Telangana']
capitals=['Chennai','Bengaluru','Cochin','Hyderabad','Hyderabad']

In [23]:
dict_states_df={'States':states,'Capital':capitals}

In [24]:
states_df=pd.DataFrame(dict_states_df)

In [25]:
states_df

       States    Capital
0  Tamil Nadu    Chennai
1   Karnataka  Bengaluru
2      Kerala     Cochin
3         A.P  Hyderabad
4   Telangana  Hyderabad

In [27]:
#Reading Students Performance CSV File
df_student_performance = pd.read_csv('StudentsPerformance.csv')

In [29]:
#showing first 5 rows
df_student_performance.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [30]:
#showing last 5 rows
df_student_performance.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [31]:
#showing first 5 rows
df_student_performance.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [32]:
#showing last 10 rows
df_student_performance.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [36]:
#getting access to shape attribute
df_student_performance.shape #gives the number of rows and columns

(1000, 8)

In [45]:
#Sets the max row display to 1000
pd.set_option('display.max_rows',1000)
# df_student_performance # --> uncomment this line

# Attributes
## - shape
## - index
## - columns
## - dtypes

In [40]:
df_student_performance.index

RangeIndex(start=0, stop=1000, step=1)

In [41]:
df_student_performance.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [42]:
df_student_performance.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods
## - head()
## - tail()
## - info()
## - describe()

In [43]:
df_student_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [44]:
df_student_performance.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions