# Dataframe

In [2]:
import pandas as pd
import numpy as np

In [18]:
# creating an array

# 1st way of creating an array
# data = np.array([["Ashwin",32],["Niveda",33],["Julia",23]])

# 2nd way of creating an array
data = [["Vedhanth",5],["Ashwin",32],["Niveda",33],["Jayanthi",59],["Julia",23],["Aravinth",32]]

In [19]:
# creating a dataframe
df = pd.DataFrame(data,index=['1','2','3','4','5','6'],columns=['Name','Age'])

In [20]:
# display dataframe
df

       Name  Age
1  Vedhanth    5
2    Ashwin   32
3    Niveda   33
4  Jayanthi   59
5     Julia   23
6  Aravinth   32

In [22]:
states=['Tamil Nadu','Karnataka','Kerala','A.P','Telangana']
capitals=['Chennai','Bengaluru','Cochin','Hyderabad','Hyderabad']

In [23]:
dict_states_df={'States':states,'Capital':capitals}

In [24]:
states_df=pd.DataFrame(dict_states_df)

In [25]:
states_df

       States    Capital
0  Tamil Nadu    Chennai
1   Karnataka  Bengaluru
2      Kerala     Cochin
3         A.P  Hyderabad
4   Telangana  Hyderabad